package:
  name: qtpy
  version: {{ GIT_DESCRIBE_TAG|replace('v', '') }}

build:
  noarch_python: True
  number: {{ GIT_DESCRIBE_NUMBER|int }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - qtpy
  requires:
    - pyqt

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: Provides an uniform layer to support PyQt4, PyQt5 and PySide with a single codebase
